### PR TITLE
make Serializer and Deserializer pub and usable

### PR DESCRIPTION
**Pull request by jordens**
This is required when using serde_json_core with code that is
generic over the serde implementation, i.e. code that wants to
instantiate the Serializer/Deserializer, in the way done in
`de::from_slice` and `ser::to_slice`.

This also adds public getters for the Serializer.current_length
and Deserializer.index members.

Two obsolete/unused impls on the `Unreachable` have been removed.

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Seems fine to me, thank you!
Do you know where the error in CI comes from?
Locally I can build master fine on 1.55.0

**Comment by jordens** [comment]
No. Might be dependencies. You may be using your own older Cargo.lock.

**Comment by jordens** [comment]
A sufficient set of dependency updates that includes the breaking change are these:

```
    Updating proc-macro2 v1.0.47 -> v1.0.66
    Updating quote v1.0.23 -> v1.0.32
    Updating serde v1.0.100 -> v1.0.175
    Updating serde_derive v1.0.100 -> v1.0.175
    Updating syn v1.0.109 -> v2.0.27
```

**Comment by eldruin** [comment]
All runs fine on 1.56.0. Could you update the MSRV to 1.56.0?

**Comment by eldruin** [comment]
Great, sorry but could you also update the MSRV in the README?

**Comment by jordens** [comment]
Also `src/lib.rs`...

**Review by eldruin — APPROVED** [review]
Great, thank you for your work!

**Pull request merged**
