### PR TITLE
Newtype, variants and unit

### PR DESCRIPTION
**Pull request by MathiasKoch**
Adds ser/de for the following types:

* `unit` types, i.e `()` & `struct Test;` 
* `newtype` structs, ser/de'ing the underlying value
* Variants:
    - The `newtype_variant` format, i.e `Variant(u32)`
    - The  `struct_variant` format, i.e `Variant { x: u32, y: u16 }`

- Fixes tests and clippy warnings

This is just #25 rebased on master

### CODE REVIEW

**Comment by MathiasKoch** [comment]
Hmm.. Not sure why the CI fails here? @eldruin ?

**Comment by MathiasKoch** [comment]
Ahh...
`error[E0658]: non exhaustive is an experimental feature`

How should that be handled? Go back to the manual one, and exclude it from clippy checks?

**Comment by MathiasKoch** [comment]
I think it might be a matter of raising MSRV?

**Comment by eldruin** [comment]
I would be OK with raising the MSRV to 1.40.0.

**Pull request merged**
