### PR TITLE
Correctly handle escaped strings when parsing json strings. Fixes #30 & #31

### LINKED ISSUE #30: String escaping
As documented in https://github.com/japaric/serde-json-core/blob/238c8fe/src/lib.rs#L46, strings are not escaped in serialization. This leads to broken JSON results when e.g. a `"` character exists as part of the string content.

If someone wants to tackle this, feel free to copy the implementation from https://github.com/CosmWasm/serde-json-wasm/pull/10.

You probably need to work on unescaping at the same time (which is hard and not zero-copy) if you want `deserialize(serialize(original)) == original`. For a seralize-only use case however, escaping is an important independent step.

### LINKED ISSUE #31: Detect string end quotes correctly
Right now in `parse_str`, each `"` character is considered a JSON string terminator. This is incorrect because it ends strings even at escaped quotes. E.g.

```json
{
  "title": "hello \"world\""
}
```

is parsed as `title = "hello\"` and the rest is considered broken data.

String end detection can be implemented without unescaping strings (and thus remains zero-copy). If someone is interested to do so, feel free to re-use the implementation from https://github.com/CosmWasm/serde-json-wasm/pull/11.

### PR DESCRIPTION
**Pull request by MathiasKoch**
Correctly handle escaped strings when parsing json strings. 

Fixes #31
Fixes #30

### CODE REVIEW

**Comment by MathiasKoch** [comment]
@eldruin Could we get some of these PRs merged now? I think all 6 are good to go before a new release?

**Comment by eldruin** [comment]
@MathiasKoch Thanks for the summary. Will do. I just need to go through them in detail.

**Review by eldruin — COMMENTED** [review]
Looks good to me, thanks!
Could you add an entry to the changelog before the merge?

**Comment by MathiasKoch** [comment]
I will merge these and open a new PR with combined changelog entries

**Pull request merged**
